WebAppAPI/Models/Service.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAppAPI.Models
{
    [Table("RentalServices")]
    public class Service
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [MaxLength(45)]
        public string Name { get; set; }
        public int Price { get; set; }
        [Column("Service")]
        [MaxLength(100)]
        public string Description { get; set; }
        public bool IsAvalible { get; set; }
    }
}

WebAppAPI/Models/UpdateArgs.cs
using Microsoft.AspNetCore.Mvc;

namespace WebAppAPI.Models
{    
        public class UpdateArgs
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public int Price { get; set; }
            public string Description { get; set; }
            public bool IsAvalible { get; set; }
        }
    
}

WebAppAPI/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebAppAPI.Pages
{
    public class ContactModel : PageModel
    {
        

        public ContactModel()
        {
            
        }
        public void OnGet()
        {
        }
    }
}

WebAppAPI/Pages/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebAppAPI.DatabaseContext;
using WebAppAPI.Models;

namespace WebAppAPI.Pages
{
    public class CreateModel : PageModel
    {
        DataBaseContext dbc;

        public CreateModel(DataBaseContext dbc)
        {
            this.dbc = dbc;
        }
        [BindProperty]
        public Service service { get; set; }

        public void OnGet()
        {
        }
        public ActionResult OnPost()
        {
            if(ModelState.IsValid)
            {
                dbc.Services.Add(service);
                dbc.SaveChanges();
                return RedirectToPage("/Index");
            }
            return Page();
        }
    }
}

WebAppAPI/Pages/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebAppAPI.DatabaseContext;
using WebAppAPI.Models;

namespace WebAppAPI.Pages
{
    public class DeleteModel : PageModel
    {
        DataBaseContext dbc;
        public DeleteModel(DataBaseContext dbc)
        {
            this.dbc = dbc;
        }
        [BindProperty]
        public Service service { get; set; }

        public void OnGet(int id)
        {
            service = dbc.Services.Find(id);
        }
    }
}

WebAppAPI/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebAppAPI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebAppAPI/Pages/Hire.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebAppAPI.DatabaseContext;
using WebAppAPI.Models;

namespace WebAppAPI.Pages
{
    public class HireModel : PageModel
    {
        DataBaseContext dbc;
        
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string address { get; set; }
        public string phonenumber { get; set; }
        public string email { get; set; }
        public string zipcode { get; set; }
        public string city { get; set; }


        public HireModel(DataBaseContext dbc)
        {
            this.dbc = dbc;
        }
        [BindProperty]
        public Service service { get; set; }
        [BindProperty]
        public int total { get; set; }

        public void OnGet(int id)
        {
            service = dbc.Services.Find(id);
        }
        public ActionResult OnPostConfirm()
        {
            if (!ModelState.IsValid)
            {
                service = dbc.Services.Find(service.Id);
                service.IsAvalible = false;
                dbc.SaveChanges();
                return RedirectToPage("/Index");
            }
            return Page();
        }
    }
}

WebAppAPI/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebAppAPI.DatabaseContext;
using WebAppAPI.Models;

namespace WebAppAPI.Pages
{
    public class IndexModel : PageModel
    {
        DataBaseContext dbc { get; set; }

        public IndexModel(DataBaseContext dbc)
        {
            this.dbc = dbc;
        }

        public List<Service> services { get; set; }

        public void OnGet()
        {
            services = dbc.Services.ToList();
        }
        public ActionResult OnPostDelete(int id)
        {
            Service serviceToDelete = dbc.Services.SingleOrDefault(s => s.Id == id);
            dbc.Services.Remove(serviceToDelete);
            dbc.SaveChanges();
            return RedirectToPage("/Index");

        }
    }
}

WebAppAPI/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebAppAPI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebAppAPI/Pages/Update.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using WebAppAPI.DatabaseContext;
using WebAppAPI.Models;

namespace WebAppAPI.Pages
{
    public class UpdateModel : PageModel
    {
        DataBaseContext dbc;

        public UpdateModel(DataBaseContext dbc)
        {
            this.dbc = dbc;
        }
        [BindProperty]
        public Service service { get; set; }

        public void OnGet(int Id)
        {
            service = dbc.Services.Find(Id);
        }
        public ActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                Service serviceReg = dbc.Services.Find(service.Id);
                
                serviceReg.Name = service.Name;
                serviceReg.Price = service.Price;
                serviceReg.Description = service.Description;
                serviceReg.IsAvalible = service.IsAvalible;
                
                dbc.SaveChanges();
            }
            return RedirectToPage("/Index");
        }
    }
}

WebAppAPI/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact Info";
}
<h1>@ViewData["Title"]</h1>
<p>Abdulla Jamal</p>
<p>Algot Aktaran</p>
<p>Erik Werner</p>
<p>Marc Garpstål</p>

WebAppAPI/Pages/Create.cshtml
@page
@model WebAppAPI.Pages.CreateModel
@{


}

<form method="post">
    <p>Service</p><input asp-for="@Model.service.Name" />
    <p><span asp-validation-for="@Model.service.Name"></span></p>
    <p>Price / h</p><input asp-for="@Model.service.Price" />
    <p><span asp-validation-for="@Model.service.Price"></span></p>
    <p>Desciption</p><input class="desciption" asp-for="@Model.service.Description" />
    <p><span asp-validation-for="@Model.service.Description"></span></p>
    <p>Avalible</p><input asp-for="@Model.service.IsAvalible" />
    <p><span asp-validation-for="@Model.service.IsAvalible"></span></p>
    <button type="submit">Add service</button>
</form>

WebAppAPI/Pages/Delete.cshtml
@page
@model WebAppAPI.Pages.DeleteModel
@{
}

WebAppAPI/Pages/Hire.cshtml
@page
@model WebAppAPI.Pages.HireModel
@{
}
<div id="div1">
    <form id="updateForm" method="post">
        <input type="hidden" asp-for="@Model.service.Id" />
        <input id="price" type="hidden" asp-for="@Model.service.Price" />
        <h4 class="h4Hire">@Model.service.Name</h4>
        <p>@Model.service.Description</p>
        <p>@Model.service.Price kr / h</p>
        <p>Hours</p>
        <input id="amount" type="number" min="1" pattern="[0-9]"/>
        <button type="button" id="hours" onclick="showDiv2()">Continue</button>
    </form>
</div>


<div id="div2" style="display:none;">

    <form class="formClass" method="post">
        <input type="hidden" asp-for="@Model.service.Id" />
        <input type="hidden" asp-for="@Model.total" />
        <div class="divContainer">
            <div id="orderBox">
                <h1 class="b-display">Order</h1>

                <div class="row">
                    <div class="leftColumn1">
                        <div class="orderinfo">
                            <p>@Model.service.Name</p>
                            <div id="theAmount">
                                <p id="count"></p>
                            </div>
                            <div id="thePrice">
                                <p>à @Model.service.Price kr / h</p>
                            </div>
                        </div>
                    </div>
                    <div class="rightColumn2">
                        <p> <br /></p>
                        <p id="totalPrice"></p>
                    </div>
                </div>
            </div>

            <div id="info">
                <h1 class="b-display">Billing Information</h1>
                <div class="row">
                    <div class="leftColumn">
                        <p class="text">Firstname</p>
                        <input type="text" asp-for="@Model.firstName" required />
                        <p><span asp-validation-for="@Model.firstName"></span></p>
                        <p class="text">Address</p>
                        <input type="text" asp-for="@Model.address" required />
                        <p><span asp-validation-for="@Model.address"></span></p>
                        <p class="text">City</p>
                        <input type="text" asp-for="@Model.city" required />
                        <p><span asp-validation-for="@Model.city"></span></p>
                        <p class="text">Email</p>
                        <input type="email" asp-for="@Model.email" required />
                        <p><span asp-validation-for="@Model.email"></span></p>
                        <button id="order" type="submit" asp-page-handler="Confirm">Confirm</button>
                    </div>
                    <div class="rightColumn">
                        <p class="text">Lastname</p>
                        <input type="text" asp-for="@Model.lastName" required />
                        <p><span asp-validation-for="@Model.lastName"></span></p>
                        <p class="text">Phonenumber</p>
                        <input type="tel" asp-for="@Model.phonenumber" pattern="^\d{10}$" required />
                        <p><span asp-validation-for="@Model.phonenumber"></span></p>
                        <p class="text">Zipcode</p>
                        <input type="tel" asp-for="@Model.zipcode" pattern="^\d{5}$" required />
                        <p><span asp-validation-for="@Model.zipcode"></span></p>
                        <button type="button" onclick="return confirm('All information will be lost')" id="order2">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

WebAppAPI/Pages/Index.cshtml
@page
@using Microsoft.IdentityModel.Tokens;
@model IndexModel
@{
    ViewData["Title"] = "If you need a service, we got it";
}



<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h3><a href="/Create">Add service</a></h3>
    @foreach (Models.Service service in Model.services)
    {
        <p id="textClass">Service: @service.Name</p>
        <p id ="textClass">Price: @service.Price / h</p>
        <p id ="textClass">Description: @service.Description</p>
        @if (service.IsAvalible == true)
        {
            <p id="textClass">Available: Yes</p>
            <button class="updateButton" asp-page-handler="Hire" asp-route-id="@service.Id"><a class="linkedText" asp-page="Hire" asp-route-id="@service.Id">Hire</a></button>
        }
        else
        {
            <p id="textClass">Available: No</p>
        }
        <form method="post" asp-page-handler="Delete" asp-route-id="@service.Id">

            <button type="submit" class="delButton" onclick="return confirm('Are you sure you want to delete service : @service.Name')">
                Delete service
            </button>
            <button class="updateButton" asp-page-handler="Update" asp-route-id="@service.Id"><a class="linkedText" asp-page="Update" asp-route-id="@service.Id">Update</a></button>
        </form>

    }
</div>

WebAppAPI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"] - CWD HomePage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppAPI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/normalize.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index"><p id="textClass2">CWD HomePage</p></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index"><p id="textClass3">Home</p></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy"><p id="textClass3">Privacy</p></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Contact"><p id="textClass3">Contact Info</p></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div id="gridstructure">
        <div id="box1">
            
        </div>
        <div id="box2">
        
        </div>
        <div id="box3">
            @RenderBody()
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CWD - <a asp-area="" asp-page="/Contact">Contact info</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebAppAPI/Pages/Update.cshtml
@page
@model WebAppAPI.Pages.UpdateModel
@{
}


<form id="updateForm" method="post">
    <input type="hidden" asp-for="@Model.service.Id" />
    <p>Service</p><input asp-for="@Model.service.Name" />
    <p><span asp-validation-for="@Model.service.Name"></span></p>
    <p>Price / h</p><input asp-for="@Model.service.Price" />
    <p><span asp-validation-for="@Model.service.Price"></span></p>
    <p>Desciption</p><input class="desciption" asp-for="@Model.service.Description" />
    <p><span asp-validation-for="@Model.service.Description"></span></p>
    <p>Available</p><input asp-for="@Model.service.IsAvalible" />
    <p><span asp-validation-for="@Model.service.IsAvalible"></span></p>
    <button type="submit">Update Service </button>
</form>